# pre-commit 1.1.0 is required for `exclude`
# however `minimum_pre_commit_version` itself requires 1.15.0
minimum_pre_commit_version: "1.15.0"

# note: isort can't be applied to yt/__init__.py because it creates circular imports
exclude: "^(\
yt/extern\
|yt/frontends/stream/sample_data\
|yt/units\
|scripts\
|benchmark\
|setupext.py\
|yt/visualization/_colormap_data.py\
|yt/__init__.py\
)"

repos:

# Note that in rare cases, flynt may undo some of the formating from black.
# A stable configuration is run black last.
-   repo: https://github.com/ikamensh/flynt
    rev: '0.58'  # keep in sync with tests/lint_requirements.txt
    hooks:
    - id: flynt
-   repo: https://github.com/psf/black
    rev: 20.8b1  # keep in sync with tests/lint_requirements.txt
    hooks:
    - id: black
      language_version: python3
-   repo: https://github.com/PyCQA/isort
    rev: '5.7.0'  # keep in sync with tests/lint_requirements.txt
    hooks:
    - id: isort
      additional_dependencies: [toml]
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.8.4'  # keep in sync with tests/lint_requirements.txt
    hooks:
    - id: flake8
      additional_dependencies: [mccabe, flake8-bugbear]
